"""add_field_promo

Revision ID: 085c9656ef8a
Revises: af19eeb7a199
Create Date: 2025-11-22 23:37:06.949353

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '085c9656ef8a'
down_revision: Union[str, None] = 'af19eeb7a199'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promocode', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_promo', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('count_days', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('promocode', schema=None) as batch_op:
        batch_op.drop_column('count_days')
        batch_op.drop_column('type_promo')

    # ### end Alembic commands ###
