"""add_fields_wg_key

Revision ID: af19eeb7a199
Revises: fba5ae3d6764
Create Date: 2025-11-12 00:02:35.266098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af19eeb7a199'
down_revision: Union[str, None] = 'fba5ae3d6764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wg_public_key', sa.String(), nullable=True))

    with op.batch_alter_table('static_persons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wg_public_key', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('static_persons', schema=None) as batch_op:
        batch_op.drop_column('wg_public_key')

    with op.batch_alter_table('keys', schema=None) as batch_op:
        batch_op.drop_column('wg_public_key')

    # ### end Alembic commands ###
